CREATE DATABASE [LIBRERIA_CABS]
GO

CREATE TABLE [LIBRERIA_CABS].[dbo].[Autor] (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Nombre VARCHAR(250) NOT NULL,
  FechaNacimiento DATE NOT NULL,
  Ciudad VARCHAR(50) NOT NULL,
  Correo VARCHAR(150) NOT NULL
)
GO

CREATE TABLE [LIBRERIA_CABS].[dbo].[Editorial] (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Nombre VARCHAR(250) NOT NULL,
  DireccionCorrespondencia VARCHAR(250) NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Correo VARCHAR(150) NOT NULL,
  MaxLibroRegistrado INT NOT NULL
)
GO

CREATE TABLE [LIBRERIA_CABS].[dbo].[Libro] (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Titulo VARCHAR(150) NOT NULL,
  Anio INT NOT NULL,
  Genero VARCHAR(150) NOT NULL,
  Npaginas INT NOT NULL,
  EditorialId INT NOT NULL FOREIGN KEY REFERENCES Editorial(Id),
  AutorId INT NOT NULL FOREIGN KEY REFERENCES Autor(Id)
);
